var that=this;function __skpm_run(e,t){that.context=t;var r=function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s="./src/convertToGrayscaleCommand.js")}({"./src/convertToGrayscaleCommand.js":
/*!******************************************!*\
  !*** ./src/convertToGrayscaleCommand.js ***!
  \******************************************/
/*! exports provided: default */function(e,t,r){"use strict";r.r(t),r.d(t,"default",function(){return h});var n=r(/*! sketch */"sketch"),o=r.n(n),a=r(/*! sketch/dom */"sketch/dom"),s=r.n(a),c=r(/*! sketch/ui */"sketch/ui"),l=r.n(c),i=r(/*! ./lib/config */"./src/lib/config.js"),u=s.a.Document,f=(s.a.Shape,u.getSelectedDocument()),p=[],y=[],d=[],g=i.PartType;function h(){var e=o.a.getSelectedDocument(),t=e.selectedPage;0==e.selectedLayers.length&&(t.layers.length>0?g=i.PageType:e.pages.length>0?g=i.AllType:l.a.message("Try openning a document!")),g==i.PageType?function(){var e=f.selectedPage;e.layers.length>0?m(e):l.a.message("Try selecting a page!")}():g==i.PartType?function(){var e=o.a.getSelectedDocument().selectedLayers;e&&(T(e),b(e))}():g==i.AllType&&o.a.getSelectedDocument().pages.forEach(function(e){m(e)})}function m(e){var t=e.layers;t.forEach(function(e){"ArtBoard"===e.type?T(e.layers||[]):v(e)}),b(t)}function b(e){e?(p.forEach(function(e){e.style.fills&&e.style.fills.forEach(function(e){"Gradient"===e.fill?e.gradient.stops.forEach(function(e){e.color=x(e.color)}):e.color=x(e.color)}),e.style.borders&&e.style.borders.forEach(function(e){"Gradient"===e.fillType?e.gradient.stops.forEach(function(e){e.color=x(e.color)}):e.color=x(e.color)})}),d.forEach(function(e){var t=x(e.style.textColor);e.style.textColor=t}),y.forEach(function(e){l.a.message("This plugin doesnt work for image layers.")}),l.a.message("Converted to Grayscale successfully！")):l.a.message("Try selecting some shapes")}function T(e){e.forEach(function(e){v(e)})}function v(e){"Shape"===e.type&&p.push(e),"ShapePath"===e.type&&p.push(e),"Image"===e.type&&y.push(e),"Text"===e.type&&d.push(e),"SymbolInstance"===e.type&&(e=function e(t){if(t.symbolId){var r=f.getSymbolMasterWithID(t.symbolId);if("SymbolInstance"==r.type)e(r);else if("SymbolMaster"==r.type)return r}}(e)),T(e.layers||[])}function x(e){var t=parseInt(e.substring(e.length-2,e.length),16)/255,r=function(e){var t=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(e);return t?{r:parseInt(t[1],16),g:parseInt(t[2],16),b:parseInt(t[3],16)}:null}(e=e.substring(0,e.length-2)),n=.2126*r.r+.7152*r.g+.0722*r.b;return"rgba("+n+","+n+","+n+","+t+")"}},"./src/lib/config.js":
/*!***************************!*\
  !*** ./src/lib/config.js ***!
  \***************************/
/*! no static exports found */function(e,t){e.exports.identifier="identifier_whale_kit",e.exports.stateColor={active:"#767272",noamal:"#D8D8D8",disabled:"#857D7D"},e.exports.StateColorAmt=20,e.exports.STATE_ACTIVE="active",e.exports.STATE_DISABLED="disabled",e.exports.AllType="all",e.exports.PartType="part",e.exports.SymbolsType="symbols",e.exports.PageType="page"},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("sketch")},"sketch/dom":
/*!*****************************!*\
  !*** external "sketch/dom" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/dom")},"sketch/ui":
/*!****************************!*\
  !*** external "sketch/ui" ***!
  \****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/ui")}});"default"===e&&"function"==typeof r?r(t):r[e](t)}that.onRun=__skpm_run.bind(this,"default");