var that=this;function __skpm_run(e,t){that.context=t;var r=function(e){var t={};function r(n){if(t[n])return t[n].exports;var o=t[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,r),o.l=!0,o.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var o in e)r.d(n,o,function(t){return e[t]}.bind(null,o));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s="./src/generateTags.js")}({"./src/generateTags.js":
/*!*****************************!*\
  !*** ./src/generateTags.js ***!
  \*****************************/
/*! exports provided: default */function(e,t,r){"use strict";r.r(t),r.d(t,"default",function(){return p});var n=r(/*! ./lib/config */"./src/lib/config.js"),o=r(/*! sketch/dom */"sketch/dom").Document,a=r(/*! sketch/dom */"sketch/dom").Group,i=r(/*! sketch/dom */"sketch/dom").Text,s=r(/*! sketch/dom */"sketch/dom").Style,l=r(/*! sketch/dom */"sketch/dom").ShapePath,c=r(/*! sketch/ui */"sketch/ui"),u="",f=function(e,t){var r=new a({name:"Tags",parent:e}),n=new l({name:"tag",shapeType:l.ShapeType.Oval,frame:{x:e.frame.width+10,y:0,width:30,height:30},parent:r});n.style.fills=[{fill:s.FillType.Color,color:"#d8d8d8ff"}];var o=u||++t,c=new i({text:""+o,alignment:i.Alignment.center,frame:n.frame,parent:r,name:"text"});c.style.verticalAlignment="center",c.style.fontSize=14,c.style.lineHeight=n.frame.height,c.style.width=n.frame.width,c.style.height=n.frame.height};function p(e){var t=o.getSelectedDocument().selectedLayers;t.length>0?1==t.length?c.getInputFromUser("Please select the index of the tag:",{type:c.INPUT_TYPE.selection,possibleValues:n.TAG_INDEX},function(e,r){u=r,t.forEach(function(e,t){f(e,t)})}):t.forEach(function(e,t){f(e,t)}):c.message("Please select a layer or layers!")}},"./src/lib/config.js":
/*!***************************!*\
  !*** ./src/lib/config.js ***!
  \***************************/
/*! no static exports found */function(e,t){e.exports.identifier="identifier_whale_kit",e.exports.stateColor={active:"#767272",noamal:"#D8D8D8",disabled:"#857D7D"},e.exports.StateColorAmt=20,e.exports.STATE_ACTIVE="active",e.exports.STATE_DISABLED="disabled",e.exports.AllType="all",e.exports.PartType="part",e.exports.SymbolsType="symbols",e.exports.PageType="page",e.exports.TAG_INDEX=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]},"sketch/dom":
/*!*****************************!*\
  !*** external "sketch/dom" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/dom")},"sketch/ui":
/*!****************************!*\
  !*** external "sketch/ui" ***!
  \****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/ui")}});"default"===e&&"function"==typeof r?r(t):r[e](t)}that.onRun=__skpm_run.bind(this,"default");