var that=this;function __skpm_run(e,t){that.context=t;var r=function(e){var t={};function r(a){if(t[a])return t[a].exports;var n=t[a]={i:a,l:!1,exports:{}};return e[a].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.m=e,r.c=t,r.d=function(e,t,a){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:a})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var a=Object.create(null);if(r.r(a),Object.defineProperty(a,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var n in e)r.d(a,n,function(t){return e[t]}.bind(null,n));return a},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s="./src/operateImageCommand.js")}({"./src/operateImageCommand.js":
/*!************************************!*\
  !*** ./src/operateImageCommand.js ***!
  \************************************/
/*! no exports provided */function(e,r,a){"use strict";a.r(r);var n=a(/*! sketch */"sketch"),i=a.n(n),o=a(/*! sketch/dom */"sketch/dom"),h=a.n(o),u=h.a.Group,c=(h.a.Text,h.a.Image),f=(h.a.Rectangle,h.a.Shape,h.a.Document.getSelectedDocument()),s=f.selectedPage,d="";f.selectedLayers.forEach(function(e){return d=e});var l={image:{width:64,height:52,rate:.2},avatar:{width:65,height:78,rate:.6},carousel:{width:62,height:42,rate:.3}};if(d){var g="image";switch(d.shapeType){case"Rectangle":0!=d.points[0].cornerRadius&&(g="carousel");break;case"Oval":g="avatar"}!function(e){var r=function(e){var t=l[e],r=l[e].rate,a={};return a.width=d.frame.width*r,a.height=a.width*t.height/t.width,d.frame.height<=a.height&&(a.height=d.frame.height*r,a.width=a.height*t.width/t.height),a.x=(d.frame.width-a.width)/2,a.y=(d.frame.height-a.height)/2,a}(e),a=e+".png",n=t.plugin.urlForResourceNamed(a),i=new u({name:"image",parent:d.parent||s,frame:d.frame});d.parent=i;var o={x:0,y:0,width:d.frame.width,height:d.frame.height};d.frame=o,new c({image:n,frame:{x:r.x,y:r.y,width:r.width,height:r.height}}).parent=i}(g)}else i.a.UI.message("Please select a Rectangle！")},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("sketch")},"sketch/dom":
/*!*****************************!*\
  !*** external "sketch/dom" ***!
  \*****************************/
/*! no static exports found */function(e,t){e.exports=require("sketch/dom")}});"default"===e&&"function"==typeof r?r(t):r[e](t)}that.onRun=__skpm_run.bind(this,"default");